site_name: TOA
site_url: https://olivierspoor.github.io/toa

site_author: Olivier Spoor


theme:
  name: material

  language: nl
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.footer
    - navigation.expand
  logo: assets/logo.png
  palette:
    primary: blue grey
    accent: indigo



nav:
  - Home: index.md
  - Arduino: 
    - arduino/index.md
    - LiquidCrystal met I2C: 
      - arduino/liquidcrystal_i2c/index.md
      - arduino/liquidcrystal_i2c/nieuwkarakter.md
      - arduino/liquidcrystal_i2c/opdracht.md
  - Raspberry Pi:
    - raspberrypi/index.md
  - Biologie:
    - biologie/index.md



markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/olivierspoor
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/olivierspoor