site_name: TOA
site_url: https://olivierspoor.github.io/toa

site_author: Olivier Spoor

repo_url: https://github.com/olivierspoor/toa
edit_uri: blob/main/docs/


nav:
  - Home: index.md
  - Arduino: 
    - arduino/index.md
    - Drukknop: arduino/drukknop.md
    - LCD met i2c: arduino/lcd_i2c.md
    - RGB-LED: arduino/rgb_led.md

  - Raspberry Pi:
    - raspberrypi/index.md
  - Biologie:
    - biologie/index.md

theme:
  name: material
  language: nl
  features:
    - navigation.tabs
    - navigation.indexes
  palette:
    primary: brown
    accent: amber

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/olivierspoor
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/olivierspoor